### ISSUE TITLE
let not yet supported outside strict mode

### ISSUE THREAD

**Issue by vectortowns** [lgapontes/hey-joe#25]
D:\dev\github.com\teste>node index.js
D:\dev\github.com\teste\node_modules\hey-joe\libraries\filter.js:4
let filter = {};
^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (D:\dev\github.com\teste\node_modules\hey-joe\index.js:6:17)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)

**Comment by vectortowns** [comment]
I will explain better: when trying to run it on windows 10, with version v4.4.4 of NodeJS, I got the above error.

**Comment by lgapontes** [comment]
This is happening because you are running the project with an older version of NodeJS. In this case, I will need to add strict mode ("use strict") on the codes that use the let scope variables. While we are correcting, a palliative option is you upgrade your NodeJS.

**Comment by lgapontes** [comment]
"Use strict" added in the codes that use the "let" statement. Problem solved in version 0.1.2.

**Comment by vectortowns** [comment]
OK thank you. It's working!
